import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:http/http.dart';


import 'constence.dart';
import 'newsresponses.dart';



class  apimanage {
  static Future<Autogenerateds> gettoprated() async {
    Uri url = Uri.https(base, '3/movie/top_rated', {"api_key": apikey});
    Response sources = await http.get(url);
    try {
      var json = jsonDecode(sources.body);
      Autogenerateds topratedrespons = Autogenerateds.fromJson(
          json);
      return topratedrespons;
    } catch (e) {
      throw e;
    }
  }

}